name = "world-cup-prediction-game-local"
compatibility_date = "2026-07-07"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "worldcup_db"
database_id = "00000000-0000-0000-0000-000000000000"
preview_database_id = "worldcup_db"
